name: 'tofu check'
description: 'NaninovelのシナリオファイルにおいてTextMeshProのFontAtlasに含まれていない文字があるかどうかチェックする'
inputs:
  charactersFilePath:
    description: 'atlas characters file path'
    required: true
    default: ""
  scenarioFileDirectoryPath:
    description: 'scenario file directory path'
    required: true
    default: ""
runs:
  using: 'node20'
  main: 'dist/index.js'
