name: Node.js CI
on:
  pull_request:
    paths:
      - "src/**"
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: yarn test
